name: 'Todoist Readme Tasks List'
author: Ramakant Gangwar
description: '🚧 Updates README with your Todoist tasks list'

inputs:
  TODOIST_API_KEY:
    description: 'Your Todoist API Key'
    required: true
  TODOIST_LENGTH:
    description: 'Your Todoist Tasks length you want to fetch'
    required: false

  USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "activity"
  color: "red"
